---
apiVersion: "automationbroker.io/v1alpha1"
kind: "AutomationBroker"
metadata:
  name: automation-broker-operator
  namespace: automation-broker
spec:
  brokerImagePullPolicy: IfNotPresent
  # TODO: Need to default these to false when building for OLM
  createBrokerNamespace: false
  waitForBroker: false
  # TODO: Currently, this must match the namespace that catasb creates the
  # admin binding for SA in (at least until operator bundles become available
  # with OLM
  # TODO: Want to update the ansible to accept an env var so that the OLM
  # deployment can actually pass this through, rather than forcing the user
  # to specify it
  brokerNamespace: automation-broker
  # TODO: The existing default is way out of date, need to update. This is
  # acceptable for now
  brokerImage: docker.io/ansibleplaybookbundle/origin-ansible-service-broker:v3.11
  ##############################################################################
  # TODO: Need to figure out why ansible runner keeps locking up while
  # building the broker_config. In the meantime, forcing this to be true will
  # allow the ansible to run
  brokerLocalOpenshiftEnabled: true
  ##############################################################################

################################################################################
# Some other example overrides, in general most defaults will work.
################################################################################
#  brokerName: automation-broker
#  brokerImage: "ansibleplaybookbundle/origin-ansible-service-broker"
#  brokerClusterRole: admin
#  brokerNodeSelector: ""
#  brokerConfig:
#    dao:
#      type: crd
#    log:
#      logfile: /var/log/ansible-service-broker/asb.log
#      stdout: true
#      level: debug
#      color: true
#    openshift:
#      imagePullPolicy: Always
#      sandboxRole: edit
#      namespace: automation-broker
#      keepNamespace: false
#      keepNamespaceOnError: true
#    broker:
#      devBroker: false
#      bootstrapOnStartup: true
#      refreshInterval: 60s
#      launchApbOnBind: false
#      outputRequest: false
#      recovery: true
#      sslCertKey: /etc/tls/private/tls.key
#      sslCert: /etc/tls/private/tls.crt
#      autoEscalate: true
#      auth:
#        - type: basic
#          enabled: false
#    registry:
#      - type: dockerhub
#        name: hc
#        url: https://registry.hub.docker.com
#        org: homecluster
#        tag: latest
#        whiteList: [ ".*" ]
