---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: access-{{ broker_name }}-role
rules:
- nonResourceURLs:
    - "/{{ broker_namespace }}"
    - "/{{ broker_namespace }}/*"
  verbs:
    - "get"
    - "post"
    - "put"
    - "patch"
    - "delete"
